### ISSUE TITLE
LMS 511 

### ISSUE THREAD

**Issue by WangQJuan** [SICKAG/sick_scan#101]
Hello, I'd like to ask about whether the running status of the laser body is sent to the driver. For example, the status of the laser body indicator light

**Comment by michael1309** [comment]
During setup phase you can use 'sRN SCdevicestate' to check the state. During measurement phase (i.e. datagrams are received) you can derive the health status indirectly: If you can not receive ros message for e.g. one second something went wrong.

**Comment by WangQJuan** [comment]
hi michael1309 
Failure state of ontology is not resolved in this driver? I want to get the state of the body directly

Thank you very much.
