### ISSUE TITLE
Can't connect to MRS1000 via Ethernet in Ubuntu

### ISSUE THREAD

**Issue by staycoolish** [SICKAG/sick_scan#104]
Hello, I'm trying to connect MRS1000 to ROS. In Windows, it works, as seen in the figure.
![ip1](https://user-images.githubusercontent.com/47630638/95390238-c0d71000-08fd-11eb-92c5-688fed34f8cf.png)

In Ubuntu, I couldn't make connection possible. First I wrote **ifconfig** and determined that the ip of Camera is 192.168.1.33, then I made a new connection at **192.168.1.34** (wrote 255.255.255.0 for netmask and left gateway empty). Now, if I write ifconfig, here is the result:
![ifconfig](https://user-images.githubusercontent.com/47630638/95390675-71ddaa80-08fe-11eb-94b5-4bb202f9b6e2.png)

And if I write **nc -z -v -w5 192.168.1.34 2112** or **nc -z -v -w5 192.168.1.34 2111** , it says:
**nc: connect to 192.168.1.34 port 2112 (tcp) failed: Connection refused**

Naturally, sick scan cannot connect to that ip address and after 5000 ms, it gives an error.

What am I missing? By the way, when I connect ethernet, wifi doesn't work, although I'm not sure if that's related to my problem.

Thanks,

**Comment by michael1309** [comment]
Did you check your firewall settings? 
Please ask your network admin. Btw this issue is  not ROS related.
