### ISSUE TITLE
Port 2112 or 2111 is not created (Device is not seen.).

### ISSUE THREAD

**Issue by staycoolish** [SICKAG/sick_scan#106]
Hello, I am trying to connect to MRS1000 via ethernet, and could not do it. I created a new connection in Ubuntu, set ip to 192.168.1.24 (the camera has 192.168.1.9), and netmask to 255.255.255.0, left gateway empty. The problem is, port 2111 or 2112 is not created. When I write nmap 192.168.1.24 , only 22/tcp is returned. Similarly, if I write 192.168.1.9 , only 22/tcp is returned, as seen in the figure. Do you have any idea why that happens? By the way, in Windows Sopas is working flawlessly, and I would like to fix the problem in Ubuntu, because finally we will connect the lidar to a computer that won't have Windows, but only Linux. Thank you.

![screen](https://user-images.githubusercontent.com/47630638/95579159-ca679180-0a3d-11eb-9fe2-3dbbeab581c5.png)

By the way, I tried generic device finder, and I set ip address as 192.168.1.255, 192.168.1.24, 192.168.1.9 , etc. I always get 
```
UDP target IP: 192.168.1.255
UDP target port: 30718
The scan result is available in 10 seconds.
Unhandled exception in thread started by 
herewego@hereWeGo:~$ 
```
I think Ubuntu cannot see the device, but I really don't know why. I already installed sick_scan, are there any additional drivers for Ubuntu?

**Comment by michael1309** [comment]
Could you solve this problem? Maybe this is a firewall problem. It seems that this is not a driver problem.

**Comment by staycoolish** [comment]
Thanks for the reply. No, the problem still exists but I think the reason is different. I don't know much about IP addresses. I know that we should **define a separate IP** , but I guess I **duplicated the IP address (i.e., defined another )of the computer** somehow. Let me show you what I got: 
![1](https://user-images.githubusercontent.com/47630638/95962323-e6d54680-0e0e-11eb-85d6-d05190d7555c.png)
![2](https://user-images.githubusercontent.com/47630638/95962407-02405180-0e0f-11eb-93b9-188ac7d88d39.png)
![3](https://user-images.githubusercontent.com/47630638/95962436-0a988c80-0e0f-11eb-9220-a7e8d0284d81.png)

I think I might be missing a valid IP address, what do you think? If I write nmap for **192.168.1.9** (IP of computer) and **192.168.1.24** (I defined it) , I get the exact same result, **only 1 port available: 22/tcp**. I also verified that firewall is inactive.
![4](https://user-images.githubusercontent.com/47630638/95962832-901c3c80-0e0f-11eb-971c-c2e0b11d20af.png)

If I should create a new IP, could you briefly describe what I should do? I try to add another connection by **+ button** at wired, but I think that just replicates the same connection. Also, I guess if there are more than 1 connection for the same MAC address, only 1 of them is activated.

**Comment by staycoolish** [comment]
At the bottom of IPv4 configurations, there is an option: 
**Use this connection only for resources on its network.** 
Enabling that solved the problem.
