### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by schleptech** [SICKAG/sick_scan#107]
Getting attached error. Can you please help with why catkin_make is not working correctly? Following your directions. 
<img width="605" alt="Screen Shot 2020-10-13 at 11 08 58 PM" src="https://user-images.githubusercontent.com/71199728/95942624-4436ac80-0da9-11eb-850a-eecddeccdc4c.png">

**Comment by michael1309** [comment]
Did you start this command on the Raspberry?

Please ensure, that the directory
```
/home/pi/ros_catkin_ws/src
```
just contains `sick_scan` for your test.

**Comment by michael1309** [comment]
Maybe there are more projects installed in parallel. These projects can contain a package.xml without catkin-dependencies.

**Comment by schleptech** [comment]
You were correct - I had not removed all the original projects from installing ROS originally. I removed all the projects except for sick_scan. This worked. Thank you
