### ISSUE TITLE
How to turn OFF port 22 [ssh] on sick lidar tim551?

### ISSUE THREAD

**Issue by HappySamuel** [SICKAG/sick_scan#108]
Hi

Due to security requirement, my client is asking if i can turn OFF the port 22 [ssh] for the sick lidars TiM551. How shall i do that? Or i shouldn't? What's the usage for this port 22 [ssh] sick lidar for?

Best,
Samuel
samuel@shadoev.com

**Comment by stg710** [comment]
The port 22 is not used by the ROS driver. It's not possible to deactivate it. You can still block it from your switch.

**Comment by HappySamuel** [comment]
Hi @stg710 

Thanks for the clarification and guidance.

Best,
Samuel
