### ISSUE TITLE
sick_scan fail catkin on windows

### ISSUE THREAD

**Issue by cax94** [SICKAG/sick_scan#111]
Hi,
I'm new to ROS on windows.
I'm trying to install sick driver sick_scan for an MRS6000 on windows. I've installed ros release noetic, catkin_tools and visual studio 2019. When I'm run catkin_make command in the catkin workspace it seems all going well when at a certain point it fails.
It gives me an error in which it tells me that when it is building **cpl_converter.cpp** it find **spritnf and fopen** which are not unsafe. I resolve that error adding in the CMakeList.txt:
_if(MSVC)
    add_definitions(-D_CRT_SECURE_NO_WARNINGS)
endif()_ 
After that, the error disappears but it fails giving me the error:

[62/96] Building CXX object sick_scan\CMakeFiles\sick_scan_lib.dir\driver\src\tcp\tcp.cpp.obj
FAILED: sick_scan/CMakeFiles/sick_scan_lib.dir/driver/src/tcp/tcp.cpp.obj
C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\cl.exe  /nologo /TP -DNOMINMAX -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"sick_scan\" -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -Dsick_scan_lib_EXPORTS -IC:\Users\admin\ros_catkin_ws\src\sick_scan\include -IC:\Users\admin\ros_catkin_ws\src\sick_scan\include\tinyxml -IC:\opt\ros\noetic\x64\include -IC:\opt\ros\noetic\x64\share\xmlrpcpp\cmake\..\..\..\include\xmlrpcpp -IC:\opt\ros\noetic\x64\include\eigen3 -IC:\Users\admin\ros_catkin_ws\src\sick_scan\include\sick_scan -IC:\Users\admin\ros_catkin_ws\devel\include -IC:\Users\admin\ros_catkin_ws\src\sick_scan\BEFORE /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /Zi /O2 /Ob1 /DNDEBUG   /D _VARIADIC_MAX=10 /Zc:__cplusplus /showIncludes /Fosick_scan\CMakeFiles\sick_scan_lib.dir\driver\src\tcp\tcp.cpp.obj /Fdsick_scan\CMakeFiles\sick_scan_lib.dir\ /FS -c C:\Users\admin\ros_catkin_ws\src\sick_scan\driver\src\tcp\tcp.cpp

Then, it tries to continue the build but after other similar errors it gives me
ninja: build stopped: subcommand failed.
Invoking "ninja -j8 -v" failed_

If I have to provide you with other information tell me and I immediately try to write in that thread. 
Thanks in advance

**Comment by michael1309** [comment]
I think you have run into a general ROS problem here. This is not directly related to sick_scan. We know this kind of error from the Windows environment.  I recommend you to test ROS under Linux. You can use e.g. WSL for this under Windows (see e.g. https://jack-kawell.com/2019/06/24/ros-wsl1/ ).
or you use a virtual machine (e.g. VmWare) together with e.g. Ubuntu.

**Comment by cax94** [comment]
Hi micheal
Thanks for the help, it is not what I really need but through the WSL I solved my problems.
Thanks!!!
