### ISSUE TITLE
About LaserScan when using single layer LiDAR.

### ISSUE THREAD

**Issue by Dai-Higashiyama** [SICKAG/sick_scan#119]
Hello,
We are considering the introduction of sick_scan for a simple measuring device using LMS511.
I was thinking of using LaserScan, but the Package Summary on the ROS Wiki says "The LaserScan data should only be used for debugging purposes."
However, as far as I read the explanation, I can see that there is a problem with multi-layer LiDAR like MRS1104, but it seems that there is no problem with single layer LiDAR like LMS511.
If I only use LMS511, is there a problem with using LaserScan?

**Comment by michael1309** [comment]
Hello @Dai-Higashiyama 

The laserScan support is obsolete, we recommend using the PointCloud messages as they also support multi layer scanners. In addition, the PointCloud messages support no-equidistant samples such as those generated by a NAV310 with angle correction.

At your request, we have just tested the LaserScan messages of an LMS511, and can confirm that they work with the current software version (1.7.8 https://github.com/SICKAG/sick_scan/commit/13ddf2aeb23be3dba12ed6aaccbc2fd2ce3fbdf3) .
This should also work for the other Lidar Sensors. This support is not regularly tested by us during development.

Best regards
