### ISSUE TITLE
Rviz error

### ISSUE THREAD

**Issue by shubhankarpataskar** [SICKAG/sick_scan#122]
I face an error while i run the 
rosrun rviz rviz 
The status shows error once the topic /scan is selected. 

![Screenshot from 2021-05-05 08-05-18](https://user-images.githubusercontent.com/34801128/117164327-5f82fc80-ad79-11eb-8376-3e9df377161d.png)
 
Is there any solution you guys can help me with?

**Comment by rostest** [comment]
sick_scan publishes with frame id "cloud". Please select cloud in the rviz "Fixed Frame" field to solve the error:
![emulator_lms7xx_screenshot](https://user-images.githubusercontent.com/46743496/117251378-e0f39100-ae44-11eb-87c0-0718cffa260e.png)

**Comment by shubhankarpataskar** [comment]
Thank you!
worked perfectly.
Also how did you get the detection field to be displayed?

**Comment by rostest** [comment]
Thanks for your feedback. Just add a MarkerArray in rviz to display the detection field:
![tim7xxs_screenshot01](https://user-images.githubusercontent.com/46743496/117339726-5d678d80-aea0-11eb-90a3-2388eb649003.png)
You can find more details about field monitoring for LMS1xx, LMS5xx, TiM7xx and TiM7xxS in https://github.com/SICKAG/sick_scan/blob/master/doc/field_monitoring_extensions.md

**Comment by shubhankarpataskar** [comment]
I do not get the option, under 
/sick_tim (im using TIM 581). I get all these options:
![Screenshot from 2021-05-06 10-33-53](https://user-images.githubusercontent.com/34801128/117341280-c62a1800-ae56-11eb-9916-bd17f139a915.png)

**Comment by rostest** [comment]
Detection fields and field monitoring are only supported for LMS1xx, LMS5xx, TiM7xx and TiM7xxS, not for TIM 581.

**Comment by shubhankarpataskar** [comment]
Okay, Thank you!
