### ISSUE TITLE
Values interpretation on output_state and output_counter

### ISSUE THREAD

**Issue by honyu-sick** [SICKAG/sick_scan#125]
Dear Support Team,

I believe the output_state and output_count in the /lidoutputstate changes when there is something detected in the field of interested but I am not sure how to interpret the values properly. For example, what does each output_state value [1,1,0,1] and output_count value [50,117,86,7] represent?

Here's the sample code example.

A sample of the /lidoutputstat is as follows:

header: 
  seq: 326
  stamp: 
    secs: 1621239590
    nsecs: 976389923
  frame_id: "sick_tim_7xxS"
version_number: 0
system_counter: 2773606000
**output_state: [1, 1, 0, 1]
output_count: [50, 117, 86, 7]**
time_state: 0
year: 0
month: 0
day: 0
hour: 0
minute: 0
second: 0
microsecond: 0

​A sample of the /lferec is as follows:

   version_number: 1 
    field_index: 3
    sys_count: 0
    dist_scale_factor: 1.0
    dist_scale_offset: 0.0
    angle_scale_factor: 3333
    angle_scale_offset: -450000
    field_result_mrs: 1
    time_state: 1
    year: 1970
    month: 1
    day: 1
    hour: 0
    minute: 56
    second: 12
    microsecond: 717000

Regards
Hon

**Comment by michael1309** [comment]
Hello,

the logic follows the description and the display in SOPAS ET. The states are as follows:
0: invalid
1: clear
2: infringed
The counts are incremented each time the fields were previously "infringed" and then clear for a certain amount of time (a few seconds).

The time information in the message part is derived from the data fields of the SOPAS message and has no direct relation to the PC time or ROS time.
