### ISSUE TITLE
TiM240 - 90° shift of scan compared to point cloud in rviz

### ISSUE THREAD

**Issue by reinbja** [SICKAG/sick_scan#138]
![image](https://user-images.githubusercontent.com/65226497/128329648-dabdc390-e833-494a-8f25-7abf60100e4b.png)

Behavior checked with LMS5xx. There, both are looking the same.

**Comment by michael1309** [comment]
Hello @reinbja,

we were able to reproduce the behavior you described and fix it. thank you very much for your comment.
