### ISSUE TITLE
Sick MRS 1000 connection issues

### ISSUE THREAD

**Issue by LOKAKSHAI** [SICKAG/sick_scan#139]
[ERROR] [1629271283.250115956]: no answer received after 5000 ms. Maybe sopas mode is

**Comment by LOKAKSHAI** [comment]
[ WARN] [1629271289.200894543]: Disconnecting TCP-Connection.

[ERROR] [1629271283.251015546]: Error Access Mode

**Comment by LOKAKSHAI** [comment]
1629271271.6345 ERROR: Tcp::open: Failed to open TCP connection to 192.168.255.20, aborting.

**Comment by michael1309** [comment]
see comments in #140.
