### ISSUE TITLE
In the process of using, I encountered that the driver occupies a high memory, resulting in the driver being killed by the system,  Whether the ROS driver is related to the reception buf [65536] of the.  If the system is stuck, will the buf be used up.  If you have encountered this or similar situation, please let me know. Or other solutions, guess

### ISSUE THREAD

**Issue by WangQJuan** [SICKAG/sick_scan#149]
![Uploading image.png…]()
Oct  8 06:47:29 robot kernel: [929077.302134] [ 8764]  1000  8764  1242209  1076014  8912896     2719             0 sick_generic_ca

**Comment by michael1309** [comment]
This belongs to #148. We are still waiting for more background information. Nevertheless we recommend to switch to sick_scan_xd (see https://github.com/SICKAG/sick_scan_xd ).

**Comment by michael1309** [comment]
Closed due to inactivity.
