### ISSUE TITLE
Sick Ranger3 

### ISSUE THREAD

**Issue by pratiksparwatwar** [SICKAG/sick_scan#153]
Do you have a repo for Sick Ranger 3 for Ubuntu. 
I need to work with Ranger3 and I only have windows sdk. 
Please share any info for using Ranger3 camera with ubuntu 18.04

**Comment by heizmreSICKAG** [comment]
Our SW-support for Ranger3 is for Windows only. There is no Linux support, yet. 
In case of application support for Ranger3 please contact https://supportportal.sick.com
