### ISSUE TITLE
How should I configure the frequency and resolution？

### ISSUE THREAD

**Issue by chance2006** [SICKAG/sick_scan#156]
Dear Sir/Lady:
As we know, we could set the angle resolution and scaning frequency of LMS5XX by edit        
        <param name="ang_res" type="double" value="0.1667" />
        <param name="scan_freq" type="double" value="25" />
but, I can't find these two paramaters in the launch file of LMS1XX, Could you kindly share a method？

Thanks very much！
 
Bob

**Comment by smartMLE** [comment]
We will support this feature in next sick_scan_xd-release, which will be released at latest until Wednesday (19th Jan 2022). 
Please use the repo. https://github.com/SICKAG/sick_scan_xd
