### ISSUE TITLE
Publication frequency drop with SICK LD-MRS 420201

### ISSUE THREAD

**Issue by Thomas-Merlet** [SICKAG/sick_scan#161]
Hello,

I'm using SICK LD-MRS 420201 sensors and currently experience publication frequency drop in certain conditions where the environment is complex (such as a forest...)

The ROS driver ouptut the following error when the frequency drop occurs:
![Screenshot from 2022-04-12 18-08-33](https://user-images.githubusercontent.com/26826861/166695568-1ea21fdf-70ad-4e67-83b3-bbf7b609d2d2.png)
I'm operating the sensors at 12.5Hz, the frequency drops to about 5-6Hz. 

In the meatime, I can see sometimes the following warning. I don't know if it is related:
![Screenshot from 2022-04-12 18-05-12](https://user-images.githubusercontent.com/26826861/166695762-c7330e95-f44a-484a-9e4a-36feb8c1e51a.png)

I have the following questions:
- I'm not using the object detection features of the sensor, but only the raw pointcloud with data tags such as ground or clutter. I thought to disable the object detection feature if it is possible, to improve the performance. 
- What other solutions could be explored to solve this problem?

  

**Current configuration**
ROS Melodic
Ubuntu 18.04 LTS
sick_scan commit tag: 58b0a45

  

Thanks for tyour help

**Comment by rostest** [comment]
Thanks for reporting. The error message indicates a data overload on the CAN interface. As you already suggested, try to reduce the data rate by disabling object detection and other features. We would like to close the issue since it's beyond the scope of the driver.
