### ISSUE TITLE
Error occurred

### ISSUE THREAD

**Issue by gguljam1** [SICKAG/sick_scan#163]
While I connect to Tim561, there were few errors occurred.
May I ask why it can happen? 
Here are the logs below.

synaps-ki@synapski-System-Product-Name:~/isaac/sdk$ bazel build //packages/sick_lidar_2d/apps:tim5xx_sample
INFO: Repository com_sickag_ssbl instantiated at:
   no stack (--record_rule_instantiation_callstack not enabled) Repository rule http_archive defined at:
   
/home/synaps-ki/.cache/bazel/_bazel_synaps-ki/75e02f31c264fa40aee99080978dd855/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: 
in <toplevel>
INFO: Repository 'com_sickag_ssbl' used the following cache hits instead of downloading the corresponding file.
  * Hash
'38d3982a130349b5983b93046bab9522d3bb7a551ee82116118d0d2c1605119f' for [https://urldefense.com/v3/__https://github.com/SickScan/sick_scan_base/archive/V0.0.2.tar.gz__;!!BXYwEpu2!qoPqAi0tyiS7olwpCkXnjsqKbUgrqpQ180UgvEcaMvb8r5EN0GtKWgjerzRzHhabM6P7Uyol0-nrRA$](https://urldefense.com/v3/__https:/github.com/SickScan/sick_scan_base/archive/V0.0.2.tar.gz__;!!BXYwEpu2!qoPqAi0tyiS7olwpCkXnjsqKbUgrqpQ180UgvEcaMvb8r5EN0GtKWgjerzRzHhabM6P7Uyol0-nrRA$)
If the definition of 'com_sickag_ssbl' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository
'com_sickag_ssbl':
    Traceback (most recent call last):
	File
"/home/synaps-ki/.cache/bazel/_bazel_synaps-ki/75e02f31c264fa40aee99080978dd855/external/bazel_tools/tools/build_defs/repo/http.bzl",
line 120
		workspace_and_buildfile(ctx)
	File
"/home/synaps-ki/.cache/bazel/_bazel_synaps-ki/75e02f31c264fa40aee99080978dd855/external/bazel_tools/tools/build_defs/repo/utils.bzl",
line 58, in workspace_and_buildfile
		ctx.file("BUILD.bazel", <1 more arguments>)
	File
"/home/synaps-ki/.cache/bazel/_bazel_synaps-ki/75e02f31c264fa40aee99080978dd855/external/bazel_tools/tools/build_defs/repo/utils.bzl",
line 58, in ctx.file
		ctx.read(ctx.attr.build_file)
Unable to load package for //:ssbl.BUILD: BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
  - /home/synaps-ki/isaac/sdk
ERROR: 
/home/synaps-ki/isaac/sdk/packages/sick_lidar_2d/components/BUILD:21:1: 
//packages/sick_lidar_2d/components:sick_lidar_2d depends on @com_sickag_ssbl//:ssbl in repository @com_sickag_ssbl which failed to fetch. no such package '@com_sickag_ssbl//': Traceback (most recent call
last):
	File
"/home/synaps-ki/.cache/bazel/_bazel_synaps-ki/75e02f31c264fa40aee99080978dd855/external/bazel_tools/tools/build_defs/repo/http.bzl",
line 120
		workspace_and_buildfile(ctx)
	File
"/home/synaps-ki/.cache/bazel/_bazel_synaps-ki/75e02f31c264fa40aee99080978dd855/external/bazel_tools/tools/build_defs/repo/utils.bzl",
line 58, in workspace_and_buildfile
		ctx.file("BUILD.bazel", <1 more arguments>)
	File
"/home/synaps-ki/.cache/bazel/_bazel_synaps-ki/75e02f31c264fa40aee99080978dd855/external/bazel_tools/tools/build_defs/repo/utils.bzl",
line 58, in ctx.file
		ctx.read(ctx.attr.build_file)
Unable to load package for //:ssbl.BUILD: BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
  - /home/synaps-ki/isaac/sdk
WARNING: errors encountered while analyzing target
'//packages/sick_lidar_2d/apps:tim5xx_sample': it will not be built
INFO: Analyzed target //packages/sick_lidar_2d/apps:tim5xx_sample (2 packages loaded, 7 targets configured).
INFO: Found 0 targets...
ERROR: command succeeded, but there were loading phase errors
INFO: Elapsed time: 0.939s, Critical Path: 0.00s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by rostest** [comment]
Thanks for reporting. I'm unsure since neither the bazel build system nor repository com_sickag_ssbl are currently supported. Maybe a cleanup of the cache folder /home/synaps-ki/.cache might help, just a guess.

We recommand use of https://github.com/SICKAG/sick_scan_xd with the build steps described in https://github.com/SICKAG/sick_scan_xd/blob/master/README.md.
