### ISSUE TITLE
the paremeter of the time_increment

### ISSUE THREAD

**Issue by 1ysine** [SICKAG/sick_scan#164]
Hi，
I got this warning when I loaded my laser.

[ WARN] [1658892163.742161966]: The time_increment, scan_time and angle_increment values reported by the scanner are inconsistent! Expected time_increment: 0.000185185, reported time_increment: 0.000061722. Perhaps you should set the parameter time_increment to the expected value. This message will print every 60 seconds.

What might be the reason?How do I solve this problem?

**Comment by rostest** [comment]
Thanks for reporting. Can you give some more information about your system - which lidar do you use? Can you send a log of all sick_scan messages from start until the error occures?
We recommend an update to https://github.com/SICKAG/sick_scan_xd. The most recent driver releases incl. improvements, fixes and new features are published in the sick_scan_xd repository.
