### ISSUE TITLE
Protective Field Infringement

### ISSUE THREAD

**Issue by fwarmuth** [SICKAG/sick_scan#165]
Hey,
i got a MRS1xxxC and want to get the field evaluations.
By default the sensor driver publishes:
```
/cloud
/encoder
/imu
/scan
/sick_mrs_1xxx/parameter_descriptions
/sick_mrs_1xxx/parameter_updates
```
How can i access the field evaluation output?
I saw issue #126, did anything change since then?

regards!

**Comment by rostest** [comment]
Field violation is not officially supported for MRS1xxx. Please contact SICK support for feature requests.
