### ISSUE TITLE
topic cloud without time stamp

### ISSUE THREAD

**Issue by iljastas** [SICKAG/sick_scan#2]
Hi guys,

in the 'pkg="sick_scan" type="sick_generic_caller"' there is missing the time stamp in the cloud.

**Comment by michael1309** [comment]
Hi, 

Thanks for your hint. We will analyse this issue and fix it in our next release (at latest end of January).

Best regards (also on the behalf of Sick),
Michael

-- 
Ing.-Büro Dr. Michael Lehning 
Schulstraße. 21B
D-31137 Hildesheim 
Germany

E: Michael.lehning@lehning.de



Am 09.01.18, 15:07, Ilja Stasewitsch <notifications@github.com> schrieb:

Hi guys,

in the 'pkg="sick_scan" type="sick_generic_caller"' there is missing the time stamp in the cloud.

**Comment by michael1309** [comment]
Hello Ilja,

the issue is fixeed now. Thank you for reporting it.

Best regards (also on the behalf of Sick),
Michael
