### ISSUE TITLE
ROS driver for Displacement measurement sensors OD Value

### ISSUE THREAD

**Issue by Andreluizfc** [SICKAG/sick_scan#22]
Hello,

I was trying to find a ROS driver for the specific OD value sensors. Does any exist? With no success, I am willing to write one from scratch. Thanks a lot.

André Castro.

**Comment by michael1309** [comment]
Hi André,

Thank you very much for your request. Unfortunately there is currently no ROS driver available for these devices from our site. Due to your request we will include the distance sensors in our considerations for the driver development in 2019.

Best regards, Michael
