### ISSUE TITLE
Melodic Release

### ISSUE THREAD

**Issue by JWhitleyAStuff** [SICKAG/sick_scan#25]
We are moving our development over to Melodic and we would like to be able to use a binary version of this driver. Any ETA on a release for Melodic?

**Comment by michael1309** [comment]
Hello,

building and creating a binary version under Melodic is no problem. You can build it and then use the binary.

**Comment by JWhitleyAStuff** [comment]
@michael1309 I was asking for SICK to create a release for Melodic using the procedure here: http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

**Comment by michael1309** [comment]
I know what you mean. We also put this issue on the task list for Jan. 2019.

**Comment by JWhitleyAStuff** [comment]
Wonderful. Thank you!

**Comment by vincentrou** [comment]
this issue was closed but it is not released for melodic ?

**Comment by JWhitleyAStuff** [comment]
@vincentrou - You're correct, I just checked and it hasn't gone into shadow-fixed yet. @michael1309 - Is this also planned for before the end of the month?

**Comment by michael1309** [comment]
We will reopen this issue and plan to start the Melodic release until end of this week.
