### ISSUE TITLE
Multiple sick tim 561 with the same ip address have mismatched data

### ISSUE THREAD

**Issue by CaptD** [SICKAG/sick_scan#38]
Hi, I have nine sick tim 561 on nine mobile robots, one on each. At first, I configured all these nine lidars with the same IP address 192.168.1.1 with SOPAS, so I can have the same launch file for all these nine robots. However, when I started these nine robots, I found lidar #1 detected points obviously from another lidar #2. And this happened for all lidars. 

Is it because of my mis-configuration, or is it common sense to avoid the same local ip address for sick tim lidars under one router?

Thanks.

**Comment by michael1309** [comment]
You must configure each scanner with its own ip address.
E.g. 192.168.1.1 for the first, 192.168.1.2 for the second and so on.
Then you must setup a launch file similiar to an extended version of
https://github.com/SICKAG/sick_scan/blob/master/launch/sick_tim_5xx_twin.launch

Also you can use the tool "https://github.com/SICKAG/sick_scan/blob/master/tools/sick_generic_device_finder/sick_generic_device_finder.py" to check your scanner setup.

**Comment by CaptD** [comment]
Thanks a lot for your helpful advice.
