### ISSUE TITLE
Unable to run catkin_make install without a crash

### ISSUE THREAD

**Issue by pol-francesch** [SICKAG/sick_scan#40]
Hello,
I am currently attempting to use a tim561 along with a Raspberry Pi 3 b. On the Raspberry Pi I am using Lubuntu and ROS kinetic. I am following the instructions for installing however whenever I run catkin_make install, or simply catkin_make it freezes the Pi such that I have to reboot it by unplugging it.
Knowing where it will freeze, I can stop catkin_make and I get the error message that I will paste below. I will also include the last two lines from the compilation. 
Is it possible that the Pi is simply not powerful enough to run this install? Or do I need to install some other packages beforehand?
Thanks.

[ 63%] Building CXX object sick_scan/CMakeFiles/sick_scan_lib.dir/driver/src/sick_scan_common.cpp.o
[ 65%] Building CXX object sick_scan/CMakeFiles/sick_scan_lib.dir/driver/src/sick_scan_common_tcp.cpp.o
^CTraceback (most recent call last):
  File "/opt/ros/kinetic/bin/catkin_make", line 296, in <module>
sick_scan/CMakeFiles/sick_scan_lib.dir/build.make:350: recipe for target 'sick_scan/CMakeFiles/sick_scan_lib.dir/driver/src/sick_scan_common_tcp.cpp.o' failed
    sys.exit(main())
make[2]: *** [sick_scan/CMakeFiles/sick_scan_lib.dir/driver/src/sick_scan_common_tcp.cpp.o] Interrupt
  File "/opt/ros/kinetic/bin/catkin_make", line 240, in main
    run_command(cmd, make_path)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/catkin/builder.py", line 239, in run_command
sick_scan/CMakeFiles/sick_scan_lib.dir/build.make:86: recipe for target 'sick_scan/CMakeFiles/sick_scan_lib.dir/driver/src/sick_scan_common.cpp.o' failed
make[2]: *** [sick_scan/CMakeFiles/sick_scan_lib.dir/driver/src/sick_scan_common.cpp.o] Interrupt
CMakeFiles/Makefile2:4343: recipe for target 'sick_scan/CMakeFiles/sick_scan_lib.dir/all' failed
make[1]: *** [sick_scan/CMakeFiles/sick_scan_lib.dir/all] Interrupt
    proc.wait()
  File "/usr/lib/python2.7/subprocess.py", line 1392, in wait
Makefile:138: recipe for target 'all' failed
make: *** [all] Interrupt
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

**Comment by michael1309** [comment]
Hello,

we have not explicitly tested building under the Raspberry PI. But we know that an insufficient power supply can cause such problems. 

We recommend that you investigate the problem further.
You can have a look at the following links:
https://raspberrypi.stackexchange.com/questions/41646/crashes-under-load-how-to-investigate
https://www.datenreise.de/en/raspberry-pi-power-supply-recommendation/

Although we are very interested in the results, we consider this issue to be more of a Raspberry Pi issue. But feedback is very welcome - especially if you were able to solve the problem with these hints.
