### ISSUE TITLE
Is there a driver that can be used on Android that does not support ros?

### ISSUE THREAD

**Issue by dama219** [SICKAG/sick_scan#41]
We want to use the tim561 in the Android. But the Android does't support ros

Thanks.

**Comment by michael1309** [comment]
Hi,

there is no native support from our side. But you can proceed as follows:
a) For example, set up ROS on a PC and run a scanner with the node "sick_scan".
b) Record the data traffic with Wireshark.
c) Track in source code how the data is parsed.
d) Transfer this logic into your own program, which will do the job.

If you find another solution, please let us know.
