### ISSUE TITLE
ERROR in: sudo apt-get install ros-<rosdistro>-sick_scan

### ISSUE THREAD

**Issue by dylanDC-Combi** [SICKAG/sick_scan#46]
this command is wrong, when you run 

> apt search ros-ROS_DISTRO 

for the distro melodic it returns the package as sick-scan and not sick_scan, as a result this command only works as:

> sudo apt-get install ros-melodic-sick-scan

there are also several errors that come up as a result, I'm assuming, where ROS cannot launch the drivers either as sick_scan or sick-scan while following the quick-start guide 

![package_listing_melodic](https://user-images.githubusercontent.com/52540754/60676222-41df6600-9e76-11e9-9d52-eb1c49184e31.PNG)

**Comment by michael1309** [comment]
Good point. We will check this for the next release. Meanwhile we recommend the direct git pull from the master branch.

**Comment by michael1309** [comment]
We've checked the package names. It is the rule that the underscore is converted to a minus sign. So it is correct that you use "sudo apt-get install ros-melodic-sick-scan" for the installation.
