### ISSUE TITLE
README install from binaries

### ISSUE THREAD

**Issue by tstanfield** [SICKAG/sick_scan#52]
Hello, the README just needs a small adjustment -

https://github.com/SICKAG/sick_scan#from-binaries

The command to install the binaries has a typo

> `sudo apt-get install ros-<rosdistro>-sick_scan`
=>
> `sudo apt-get install ros-<rosdistro>-sick-scan`

This caused me some trouble. Hope this helps.

**Comment by michael1309** [comment]
Hi @tstanfield ,
Thanks for your hint. We modified the README.md.
