### ISSUE TITLE
Simulation of tim sick 561 

### ISSUE THREAD

**Issue by nagarjunvinukonda** [SICKAG/sick_scan#54]
I have been trying to simulate the working of my lidar sensor in rviz and gazebo without actually connecting the actual lidar. I just wanted to know is it actually possible to do it and if yes, where can I find the relevant package for the purpose?

Thank you

**Comment by michael1309** [comment]
Maybe you could start here with a high level simulation:
http://docs.ros.org/indigo/api/jackal_tutorials/html/simulation.html
