### ISSUE TITLE
sRN STlms

### ISSUE THREAD

**Issue by comwise** [SICKAG/sick_scan#56]
the following command:

sRN STlms
sRA STlms 3 0 8 01:21:53 A 01.01.1970 0 0 0

i get the laser status is "3",  i look up your readme

Undefined: 0
Initialization: 1
Configuration: 2
Lower case: 3
Rotating: 4
In preparation: 5
Ready: 6
Measurement active: 7

i want to know about 3(Lower case) ? why does laser ouput status 3?

i look forward your reply

**Comment by michael1309** [comment]
Good point. We do not use this command in our implementation. Please ask the SICK support. If you get any useful feedback, please feel free to publish it in this issue.

**Comment by michael1309** [comment]
@comwise Did you receive a replyfrom the support?

**Comment by michael1309** [comment]
Closed due to inactivity.
