### ISSUE TITLE
Sick Tim561 device not detecting 

### ISSUE THREAD

**Issue by austteague** [SICKAG/sick_scan#64]
I am trying to connect to a Sick Tim 561 LiDAR using sick_tim_5xx.launch. When doing so i have the following errors. The IP audress is changed in the launch file and is 169.254.172.71

austin@austin-Precision-5520:~/ros_catkin_ws$ roslaunch sick_scan sick_tim_5xx.launch
... logging to /home/austin/.ros/log/8adb6048-1c48-11ea-a1ae-b94bf9e35c82/roslaunch-austin-Precision-5520-5563.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://austin-Precision-5520:46695/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /sick_tim_5xx/cloud_topic: cloud
 * /sick_tim_5xx/frame_id: cloud
 * /sick_tim_5xx/hostname: 169.254.172.71
 * /sick_tim_5xx/intensity: True
 * /sick_tim_5xx/max_ang: 2.35619449
 * /sick_tim_5xx/min_ang: -2.35619449
 * /sick_tim_5xx/port: 2112
 * /sick_tim_5xx/range_max: 100.0
 * /sick_tim_5xx/scanner_type: sick_tim_5xx
 * /sick_tim_5xx/timelimit: 5
 * /sick_tim_5xx/use_binary_protocol: True

NODES
  /
    sick_tim_5xx (sick_scan/sick_generic_caller)

ROS_MASTER_URI=http://localhost:11311

process[sick_tim_5xx-1]: started with pid [5580]
[ INFO] [1576090913.600026808]: sick_generic_caller V. 001.003.020
[ INFO] [1576090913.600070064]: Program arguments: /home/austin/ros_catkin_ws/devel/lib/sick_scan/sick_generic_caller
[ INFO] [1576090913.600079721]: Program arguments: __name:=sick_tim_5xx
[ INFO] [1576090913.600104200]: Program arguments: __log:=/home/austin/.ros/log/8adb6048-1c48-11ea-a1ae-b94bf9e35c82/sick_tim_5xx-1.log
[ INFO] [1576090913.608229162]: Found sopas_protocol_type param overwriting default protocol:
[ INFO] [1576090913.608254610]: Binary protocol activated
[ INFO] [1576090913.608266937]: Start initialising scanner [Ip: 169.254.172.71] [Port: 2112]
[ INFO] [1576090913.634351789]: Publishing laserscan-pointcloud2 to cloud
1576090913.6374 ERROR: Tcp::open: Failed to open TCP connection to 169.254.172.71, aborting.
[ INFO] [1576090913.639255645]: Parameter setting for <active_echo: 0>
[ INFO] [1576090913.839928764]: Sending  : <STX><STX><STX><STX><Len=0023>sMN SetAccessMode 0x03 0xf4 0x72 0x47 0x44 CRC:<0xb3>
1576090913.8401 Warning: Tcp::write: Failed to send data to socket.
[ERROR] [1576090919.908813399]: no answer received after 5000 ms. Maybe sopas mode is wrong.

[ INFO] [1576090919.908940549]: sendSOPASCommand: no full reply available for read after 5000 ms
[ INFO] [1576090919.909188489]: Receiving: <STX><ETX>
[ INFO] [1576090919.909267448]: SOPAS Communication -Error unexpected Sopas Answer for request <STX><STX><STX><STX><Len=0023>sMN SetAccessMode 0x03 0xf4 0x72 0x47 0x44 CRC:<0xb3>

[ INFO] [1576090919.909547112]: Sending  : <STX>sMN SetAccessMode 3 F4724744<ETX>
1576090919.9096 Warning: Tcp::write: Failed to send data to socket.
[ERROR] [1576090926.000694232]: no answer received after 5000 ms. Maybe sopas mode is wrong.

[ INFO] [1576090926.000826998]: sendSOPASCommand: no full reply available for read after 5000 ms
[ INFO] [1576090926.001042284]: Receiving: <STX><ETX>
[ INFO] [1576090926.001114041]: SOPAS Communication -Error unexpected Sopas Answer for request <STX>sMN SetAccessMode 3 F4724744<ETX>

[ERROR] [1576090926.001280456]: Error Access Mode
[ INFO] [1576090926.201903159]: Sending  : <STX>sWN EIHstCola 1<ETX>
1576090926.2020 Warning: Tcp::write: Failed to send data to socket.
[ERROR] [1576090932.263198941]: no answer received after 5000 ms. Maybe sopas mode is wrong.

[ INFO] [1576090932.263299494]: sendSOPASCommand: no full reply available for read after 5000 ms
[ INFO] [1576090932.263501296]: Receiving: <STX><ETX>
[ INFO] [1576090932.263565671]: SOPAS Communication -Error unexpected Sopas Answer for request <STX>sWN EIHstCola 1<ETX>

[ERROR] [1576090932.263724024]: Command or Error message not defined
[ INFO] [1576090932.263905386]: Failed to init scanner Error Code: 1
Waiting for timeout...
If the communication mode set in the scanner memory is different from that used by the driver, the scanner's communication mode is changed.
This requires a restart of the TCP-IP connection, which can extend the start time by up to 30 seconds. There are two ways to prevent this:
1. [Recommended] Set the communication mode with the SOPAS ET software to binary and save this setting in the scanner's EEPROM.
2. Use the parameter "use_binary_protocol" to overwrite the default settings of the driver.
[ INFO] [1576090932.264022750]: Start initialising scanner [Ip: 169.254.172.71] [Port: 2112]
[ WARN] [1576090932.264124339]: Disconnecting TCP-Connection.
sick_scan driver exiting.
[ INFO] [1576090932.319914563]: Publishing laserscan-pointcloud2 to cloud
1576090932.3225 ERROR: Tcp::open: Failed to open TCP connection to 169.254.172.71, aborting.
[ INFO] [1576090932.324637964]: Parameter setting for <active_echo: 0>
[ INFO] [1576090932.525201298]: Sending  : <STX><STX><STX><STX><Len=0023>sMN SetAccessMode 0x03 0xf4 0x72 0x47 0x44 CRC:<0xb3>
1576090932.5253 Warning: Tcp::write: Failed to send data to socket.
[ERROR] [1576090938.601870253]: no answer received after 5000 ms. Maybe sopas mode is wrong.

[ INFO] [1576090938.601967579]: sendSOPASCommand: no full reply available for read after 5000 ms
[ INFO] [1576090938.602142138]: Receiving: <STX><ETX>
[ INFO] [1576090938.602210681]: SOPAS Communication -Error unexpected Sopas Answer for request <STX><STX><STX><STX><Len=0023>sMN SetAccessMode 0x03 0xf4 0x72 0x47 0x44 CRC:<0xb3>

[ INFO] [1576090938.602536260]: Sending  : <STX>sMN SetAccessMode 3 F4724744<ETX>
1576090938.6026 Warning: Tcp::write: Failed to send data to socket.
[ERROR] [1576090944.703972546]: no answer received after 5000 ms. Maybe sopas mode is wrong.

[ INFO] [1576090944.704068575]: sendSOPASCommand: no full reply available for read after 5000 ms
[ INFO] [1576090944.704256181]: Receiving: <STX><ETX>
[ INFO] [1576090944.704316167]: SOPAS Communication -Error unexpected Sopas Answer for request <STX>sMN SetAccessMode 3 F4724744<ETX>

[ERROR] [1576090944.704397757]: Error Access Mode
[ INFO] [1576090944.904812464]: Sending  : <STX>sWN EIHstCola 1<ETX>
1576090944.9049 Warning: Tcp::write: Failed to send data to socket.
[ERROR] [1576090950.984822705]: no answer received after 5000 ms. Maybe sopas mode is wrong.

[ INFO] [1576090950.984927041]: sendSOPASCommand: no full reply available for read after 5000 ms
[ INFO] [1576090950.985132595]: Receiving: <STX><ETX>
[ INFO] [1576090950.985210738]: SOPAS Communication -Error unexpected Sopas Answer for request <STX>sWN EIHstCola 1<ETX>

[ERROR] [1576090950.985350173]: Command or Error message not defined
[ INFO] [1576090950.985489830]: Failed to init scanner Error Code: 1
Waiting for timeout...
If the communication mode set in the scanner memory is different from that used by the driver, the scanner's communication mode is changed.
This requires a restart of the TCP-IP connection, which can extend the start time by up to 30 seconds. There are two ways to prevent this:
1. [Recommended] Set the communication mode with the SOPAS ET software to binary and save this setting in the scanner's EEPROM.
2. Use the parameter "use_binary_protocol" to overwrite the default settings of the driver.
[ INFO] [1576090950.985579144]: Start initialising scanner [Ip: 169.254.172.71] [Port: 2112]
[ WARN] [1576090950.985638684]: Disconnecting TCP-Connection.
sick_scan driver exiting.
[ INFO] [1576090951.080715995]: Publishing laserscan-pointcloud2 to cloud
1576090951.0838 ERROR: Tcp::open: Failed to open TCP connection to 169.254.172.71, aborting.
[ INFO] [1576090951.085704559]: Parameter setting for <active_echo: 0>
[ INFO] [1576090951.. 286202931]: Sending  : <STX><STX><STX><STX><Len=0023>sMN SetAccessMode 0x03 0xf4 0x72 0x47 0x44 CRC:<0xb3>
1576090951.2863 Warning: Tcp::write: Failed to send data to socket.

After doing some  research I tried the following command to ping the connection and received the following output

austin@austin-Precision-5520:~/ros_catkin_ws$ nc -z -v -w5 $169.254.172.71 2112
nc: connect to 69.254.172.71 port 2112 (tcp) failed: Network is unreachable

I am new to using ubuntu and ROS and am at a loss of how to fix the issue. I am able to connect to the lidar in sopas ET and visualize everything but can not connect in ROS. 

I appreciate any and all help to resolve the issue.

**Comment by michael1309** [comment]
You must change "nc -z -v -w5 $169.254.172.71 2112" to "nc -z -v -w5 169.254.172.71 2112".
$1 is interpreted as an argument.
Due to our discussion rule, we want to close these tickets. Your problem has not really to do with sick_scan. Please ask the ubuntu forum about network problems. Please follow the first steps of troubleshooting. Please also check if you are able to ping the scanner. Disconnect the scanner and try again. In this case, an error ping will output an error. Reconnect. If the ping is successful, try to start the ros node.
