### ISSUE TITLE
`range_min` and `range_max` ignored.

### ISSUE THREAD

**Issue by themightyoarfish** [SICKAG/sick_scan#65]
Despite the fact that the launch file for LMS 5xx lists the two parameters as possible settings, actually assigning them has no effect on the pointcloud. I searched in the repo and all they seem to be used for is setting some metadata fields in a ´sensor_msgs::LaserScan` message which is not what is used for the LMS. Perhaps the documentation on these parameters should be improved.

**Comment by michael1309** [comment]
Good point. We will verify that. In principle, however, we recommend that you also check the distance in the application anyway. At least as a workaround, this is the preferred solution in this case.

**Comment by michael1309** [comment]
In the meantime we have decided not to use the parameters range_min and range_max according to your suggestion. In almost all cases known to us, this will be filtered directly in the target application if necessary.
