### ISSUE TITLE
Consider adding macros for accurate TiM 56x and 57x URDF scan specifications

### ISSUE THREAD

**Issue by MitchAllain** [SICKAG/sick_scan#67]
Hello,

One nice addition to this package would be to add URDF macros for the TiM 56x and 57x products which have the correct range and angular resolution already configured. I would be willing to open a PR for this enhancement, if there is interest in this addition?

Thanks,
Mitchell

**Comment by michael1309** [comment]
Yes, we'd like that very much. We really appreciate the support for better visualization.
