### ISSUE TITLE
Specification for time-related field of telegram structure

### ISSUE THREAD

**Issue by wonseokdjango** [SICKAG/sick_scan#76]
Dear all,

I'm writing this issue to clarify the telegram field specification of LMS151-10100.

The fields that I'm wondering are below(which are specified in [this document](https://cdn.sick.com/media/docs/7/27/927/Technical_information_Telegram_Listing_Ranging_sensors_LMS1xx_LMS5xx_TiM5xx_TiM7xx_LMS1000_MRS1000_MRS6000_NAV310_LD_OEM15xx_LD_LRS36xx_LMS4000_en_IM0045927.PDF), Telegram Listing):

- **'Time since start up in us'** field of sRA LMDscandata / sSN LMDscandata (p.71)
- **'Time info'** field of sRA LMDscandata / sSN LMDscandata (p.81)

### **Q1.** (When it is the output telegram,)

Does **'Time since start up in us'** mean the time moment when the corresponding scan is completed? or the time moment when corresponding scan is started?

When I read the document, it seems that **'Time since start up in us'** means the former.
However, in sick_scan code it seems like the later(line 2632 of sick_scan_common.cpp)

### **Q2.**
Which time moment is stored at 'Time info' field?

Is it the time moment when the telegram is transmitted? or when the scan is completed?

Please kindly be advised that I also refer the your [doc file](https://github.com/SICKAG/sick_scan/blob/master/doc/timing.md) to concretely explain the time moments(scan generation, scan transmit).

Thank you.

Best regards,

**Comment by michael1309** [comment]
Hello @wonseokdjango 
### Q1. (When it is the output telegram,)
> Does `Time since start up in us` mean the time moment when the corresponding scan is completed? or the time moment when corresponding scan is started?

The description to this field says:

> Counting  the time since power up the device; starting with 0.  In the output  telegram  this is the time at the  zero index before the measurement itself starts.

This means that this value corresponds to the start of the scan.

There is also the field `Time of transmis-sion in μs` with the description 
>Time  in μs  when the complete scan is transmitted to the buffer for data output;  starting  with 0  at scanner bootup. 

This the µS timestamp when the packet is transmitted.
In the software PLL we assume that this timestamp is correlated with the arrival of the packet in the Ros driver. So the scan start can be calculated in ROS time. With the known duration of an scan the timestamp for every shot could be calculated.

### Q2.
> Which time moment is stored at 'Time info' field?

Some scanners support absolute time stamps via NTP synchronization. If the scanner has an NTP synchronized system time, this field contains the absolute time stamp of the scan start if this field is enabled.

Best regards,

Michael
