### ISSUE TITLE
How can I get the correct timestamp of scan data?

### ISSUE THREAD

**Issue by wonseokdjango** [SICKAG/sick_scan#77]
Dear @michael1309 ,

I hope you are well.

This is a follow-up question of our [previous Q&A](https://github.com/SICKAG/sick_scan/issues/76).

I'd like to use **"Time since start up in us"** as the timestamp of the scan, so, regarding what you said, I've set up NTP-synchronization.

However, a few things are still unclear to me.
I'd really appreciate it if you could answer about the questions below:

### Q1. How can I get(read) **"Time since start up in us"** field after setting up NTP?

When I skimmed your sick_scan driver source code, I could not find the code that accesses/reads **"Time since start up in us"** field.

I thought that the function "swap_endian"(line 100 of sick_scan_common.cpp) should be invoked against the "year" and "Micor-second" sub-fields of **"Time since start up in us"**.
However, I could not find such code line from your driver.

As an alternative, I've attached my custom source code to your driver.
(which reads the last few bytes of LMDscandata telegram including **"Time since start up in us"** field)

### Q2. Is NTP-synchronization performed only once when the driver is initialized?

Since I'm quite new to the lidar sensor, I expected that LMS151 periodically polls the NTP-server.
(such as minpoll and maxpoll parameters of the usual NTP clients)

However, it seems that the function "setNTPServerAndStart"(line 1576 of sick_scan_common.cpp) performs the NTP-synchronization only once when the driver is initialized(init_scanner).

### Summary

Could you please clarify whether my understanding is correct or not?

**i.e.** 

**1st.** To read **"Time since start up in us"**, I have to implement my own custom code.
**2nd.** NTP-synchronization is performed only once when the driver is initialized(if so, is it OK to call "setNTPServerAndStart" periodically whenever I want to?).

**p.s.**

The reason why I'm focusing on **"Time since start up in us"** field is that

- Unlike your environment that you mentioned [here](https://github.com/SICKAG/sick_scan/blob/master/doc/timing.md), the network transmission delay in our environment is not negligible(up to 4msec, frequently occurs), so I'd like to use sensor-provided timestamp instead of driver-provided timestamp)

Best wishes,

**Comment by michael1309** [comment]
I guess you are correct in your assumption. Currently NTP is not fully supported by the driver. So we can only appreciate it if you implement this functionality by extending the code as you suggest.
