### ISSUE TITLE
Visualization with RViz doesn't work

### ISSUE THREAD

**Issue by philippsw** [SICKAG/sick_scan#83]
Hello everybody,

i use ROS for Ubuntu 18.04 and the SICK TIM 551 Laserscanner. The installation was succesfull and i can start the scanner without any problems. Now, i would like to visualize the measuerement data but i dont know how i get the data in RViz after start. 

In RViz is following errors:
Global Status: Warn
       Fixed Frame: No tf data. Actual error: Fixed Frame [laser] does not exist

PointCloud2
       Status: Error
             Transform[Sender = unknown_publisher]:  For Frame [cloud]: Fixed Frame [laser] does not exist

Im new at this and hope someone can help me.

**Comment by michael1309** [comment]
In rviz change 
the entry "Fix frame" from "/map" to "/laser".
![frame](https://user-images.githubusercontent.com/33296049/78117466-00c8b200-7406-11ea-8dde-e788d6cbdfd4.PNG)
