### ISSUE TITLE
PythonCode: Decode recieved message (rawData) in sick_genreric_device_finder.py

### ISSUE THREAD

**Issue by philippsw** [SICKAG/sick_scan#84]
If i started the py-file, i received this message: b'\x10\x00\x00\x08\xff\xff\xff\xff\xff\xff\xca\xa4\xf1y\x01\x02\xc0\xa8\x00~\xff\xff\xff\x00'
as rawData - can anybody help me to decode this telegram? The datasheets dont help me.

**Comment by michael1309** [comment]
The protocol of finding new scanner is not supported officially by SICK. We analyzed the ip traffic with wireshark and developed this tools just for convenience. 

Feel free to support some new results. Pull requests are also appreciated.

Regarding to: sick_scan/tools/sick_generic_device_finder/sick_generic_device_finder.py
