### ISSUE TITLE
idc file support

### ISSUE THREAD

**Issue by benmaidel** [SICKAG/sick_scan#88]
I have some *.idc files created with Sick's LaserView application. The recorded scandata origin was a Nav310. Now I am searching for a way to get the scandata from the idc files into ros. Is there a way to support idc files? Or does someone know a way to parse this file type?

**Comment by michael1309** [comment]
Currently we do not support the IDC files directly. But you can write a parser that reads the IDC files and publishes the data as Pointcloud2 data. You can use the corresponding places in the source code as a template.

You can find the code parts in the file sick_scan_common.cpp in the following section:
`
                    for (int ii = 0; ii < numChannels; ii++)
                    {
                      std::string channelId[] = {"x", "y", "z", "intensity"};
                      partialCloud.fields[ii].name = channelId[ii];
                      partialCloud.fields[ii].offset = ii * sizeof(float);
                      partialCloud.fields[ii].count = 1;
                      partialCloud.fields[ii].datatype = sensor_msgs::PointField::FLOAT32;
                    }
`

Translated with www.DeepL.com/Translator (free version)
