### ISSUE TITLE
Changed password, can no longer login

### ISSUE THREAD

**Issue by rachel-spykerman** [SICKAG/sick_scan#89]
Hi,

I'm running into a few issues with the sick_scan package as well as Sopas tool to interface with the SICK LIDAR's. I have two SICK LIDAR's set up (a front one and back one, both TiM781S). I have a top level ros launch file that sets a few parameters for each LIDAR (see attached txt file
[sick_sensors.txt](https://github.com/SICKAG/sick_scan/files/4737243/sick_sensors.txt)
) and then calls the sick_scan provided launch file for the TiM781S. I'm running into several errors when launching, the first of which seems to be an issue with logging into each LIDAR. The setAccessMode returns a 0, and subsequent errors occur with EIHstCola, LMPoutputRange, and LMDscandatacfg. I'm able to receive data on all expected topics, I can see the scans in RVIZ, and I can detect obstacles, so everything seems to be functioning correct, but I don't know how to get rid of these errors. 

Since it doesn't seem to be able to login when calling setAccessMode, I've read on another issue (https://github.com/SICKAG/sick_scan/issues/4) that the password needs to be a default password of "client". I had initially changed it to something different, but to try and fix this login issue, I tried changing it to "client" through Sopas tool, but now I'm not able to log into the LIDAR at all. Neither my old password or the "client" password work.

Two questions: 
1) How do I resolve not being able to log into the SICK LIDAR after changing the password?
2) How do I resolve the roslaunch errros? 

Please let me know if you need any more info.

Here's the roslaunch output: 

started roslaunch server http://beta1:33383/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /sick_scan_back/cloud_topic: back_cloud
 * /sick_scan_back/frame_id: /laser_back
 * /sick_scan_back/hostname: 192.168.1.204
 * /sick_scan_back/intensity: True
 * /sick_scan_back/max_ang: 2.35619449
 * /sick_scan_back/min_ang: -2.35619449
 * /sick_scan_back/port: 2112
 * /sick_scan_back/range_max: 100.0
 * /sick_scan_back/scanner_type: sick_tim_7xxS
 * /sick_scan_back/timelimit: 5
 * /sick_scan_back/use_binary_protocol: False
 * /sick_scan_front/cloud_topic: front_cloud
 * /sick_scan_front/frame_id: /laser_front
 * /sick_scan_front/hostname: 192.168.1.203
 * /sick_scan_front/intensity: True
 * /sick_scan_front/max_ang: 2.35619449
 * /sick_scan_front/min_ang: -2.35619449
 * /sick_scan_front/port: 2112
 * /sick_scan_front/range_max: 100.0
 * /sick_scan_front/scanner_type: sick_tim_7xxS
 * /sick_scan_front/timelimit: 5
 * /sick_scan_front/use_binary_protocol: False

NODES
  /
    sick_scan_back (sick_scan/sick_generic_caller)
    sick_scan_front (sick_scan/sick_generic_caller)
    zone_activation_node (sick_safety/zone_activation_node)

auto-starting new master
process[master]: started with pid [8061]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 1dc0cb7e-a744-11ea-af21-ac40ea0193f7
process[rosout-1]: started with pid [8098]
started core service [/rosout]
process[sick_scan_front-2]: started with pid [8116]
[${node}] [1591372159.553648299] [ INFO] [main():184]: sick_generic_caller V. 1.6.0
[${node}] [1591372159.553701310] [ INFO] [main():192]: Program arguments: /opt/ros/kinetic/lib/sick_scan/sick_generic_caller
[${node}] [1591372159.553715154] [ INFO] [main():192]: Program arguments: scan:=scan_front
[${node}] [1591372159.553728935] [ INFO] [main():192]: Program arguments: cloud:=cloud_front
[${node}] [1591372159.553771774] [ INFO] [main():192]: Program arguments: __name:=sick_scan_front
[${node}] [1591372159.553799879] [ INFO] [main():192]: Program arguments: __log:=/home/rachel/Dev/canvas/beta-borg/artifacts/log/1dc0cb7e-a744-11ea-af21-ac40ea0193f7/sick_scan_front-2.log
process[sick_scan_back-3]: started with pid [8117]
[${node}] [1591372159.562670592] [ INFO] [main():184]: sick_generic_caller V. 1.6.0
[${node}] [1591372159.562714863] [ INFO] [main():192]: Program arguments: /opt/ros/kinetic/lib/sick_scan/sick_generic_caller
[${node}] [1591372159.562724747] [ INFO] [main():192]: Program arguments: scan:=scan_back
[${node}] [1591372159.562732501] [ INFO] [main():192]: Program arguments: cloud:=cloud_back
[${node}] [1591372159.562741373] [ INFO] [main():192]: Program arguments: __name:=sick_scan_back
[${node}] [1591372159.562750001] [ INFO] [main():192]: Program arguments: __log:=/home/rachel/Dev/canvas/beta-borg/artifacts/log/1dc0cb7e-a744-11ea-af21-ac40ea0193f7/sick_scan_back-3.log
process[zone_activation_node-4]: started with pid [8134]
[/sick_scan_front] [1591372159.567793692] [ INFO] [__cxx11::string)():281]: Found sopas_protocol_type param overwriting default protocol:
[/sick_scan_front] [1591372159.567836856] [ INFO] [__cxx11::string)():298]: ASCII protocol activated
[/sick_scan_front] [1591372159.567865382] [ INFO] [__cxx11::string)():324]: Start initialising scanner [Ip: 192.168.1.203] [Port: 2112]
[/sick_scan_back] [1591372159.581994635] [ INFO] [__cxx11::string)():281]: Found sopas_protocol_type param overwriting default protocol:
[/sick_scan_back] [1591372159.582032748] [ INFO] [__cxx11::string)():298]: ASCII protocol activated
[/sick_scan_back] [1591372159.582056631] [ INFO] [__cxx11::string)():324]: Start initialising scanner [Ip: 192.168.1.204] [Port: 2112]
[/sick_scan_front] [1591372159.631528818] [ INFO] [SickScanCommon::SickScanCommon():376]: Publishing laserscan-pointcloud2 to front_cloud
[/sick_scan_front] [1591372159.641799860] [ INFO] [SickScanCommon::init_scanner():1155]: Parameter setting for <active_echo: 0>
[/sick_scan_back] [1591372159.643464884] [ INFO] [SickScanCommon::SickScanCommon():376]: Publishing laserscan-pointcloud2 to back_cloud
[/sick_scan_back] [1591372159.655560964] [ INFO] [SickScanCommon::init_scanner():1155]: Parameter setting for <active_echo: 0>
[/sick_scan_front] [1591372159.842709045] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sMN SetAccessMode 3 6FD62C05<ETX>
[/sick_scan_front] [1591372159.845071178] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sAN SetAccessMode 0<ETX>
[/sick_scan_back] [1591372159.856260310] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sMN SetAccessMode 3 6FD62C05<ETX>
[/sick_scan_back] [1591372159.858491735] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sAN SetAccessMode 0<ETX>
[/sick_scan_front] [1591372160.045263582] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sWN EIHstCola 0<ETX>
[/sick_scan_front] [1591372160.047626319] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sFA A<ETX>
[/sick_scan_front] [1591372160.047704966] [ERROR] [SickScanCommon::sendSopasAndCheckAnswer():750]: Error Sopas answer mismatch Error unexpected Sopas Answer for request <STX>sWN EIHstCola 0<ETX>Answer= >>>sFA A<<<

[/sick_scan_front] [1591372160.047807429] [ERROR] [SickScanCommon::init_scanner():1312]: Command or Error message not defined
[/sick_scan_back] [1591372160.058720308] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sWN EIHstCola 0<ETX>
[/sick_scan_back] [1591372160.061073185] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sFA A<ETX>
[/sick_scan_back] [1591372160.061149420] [ERROR] [SickScanCommon::sendSopasAndCheckAnswer():750]: Error Sopas answer mismatch Error unexpected Sopas Answer for request <STX>sWN EIHstCola 0<ETX>Answer= >>>sFA A<<<

[/sick_scan_back] [1591372160.061208200] [ERROR] [SickScanCommon::init_scanner():1312]: Command or Error message not defined
[/sick_scan_front] [1591372160.248040984] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sRN FirmwareVersion<ETX>
[/sick_scan_front] [1591372160.250499804] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sRA FirmwareVersion 5 V3.13<ETX>
[/sick_scan_back] [1591372160.261423484] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sRN FirmwareVersion<ETX>
[/sick_scan_back] [1591372160.263822162] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sRA FirmwareVersion 5 V3.13<ETX>
[/sick_scan_front] [1591372160.450749277] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sRN SCdevicestate<ETX>
[/sick_scan_front] [1591372160.453093571] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sRA SCdevicestate 1<ETX>
[/sick_scan_back] [1591372160.464056838] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sRN SCdevicestate<ETX>
[/sick_scan_back] [1591372160.466345797] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sRA SCdevicestate 1<ETX>
[/sick_scan_front] [1591372160.653345615] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sRN ODoprh<ETX>
[/sick_scan_front] [1591372160.655724654] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sRA ODoprh 6179<ETX>
[/sick_scan_back] [1591372160.666544818] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sRN ODoprh<ETX>
[/sick_scan_back] [1591372160.668818879] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sRA ODoprh 6152<ETX>
[/sick_scan_front] [1591372160.857524908] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sRN ODpwrc<ETX>
[/sick_scan_front] [1591372160.859897635] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sRA ODpwrc 140<ETX>
[/sick_scan_back] [1591372160.870126807] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sRN ODpwrc<ETX>
[/sick_scan_back] [1591372160.872517797] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sRA ODpwrc 109<ETX>
[/sick_scan_front] [1591372161.061609026] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sRN LocationName<ETX>
[/sick_scan_front] [1591372161.064022481] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sRA LocationName B beta1-front<ETX>
[/sick_scan_front] [1591372161.065612768] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sRN LMPoutputRange<ETX>
[/sick_scan_front] [1591372161.066801011] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sRA LMPoutputRange 1 D05 FFF92230 225510<ETX>
[/sick_scan_front] [1591372161.066877431] [ INFO] [SickScanCommon::init_scanner():1721]: Angle resolution of scanner is 0.33330 [deg]  (in 1/10000th deg: 0xD05)
[/sick_scan_front] [1591372161.066920096] [ INFO] [SickScanCommon::init_scanner():1723]: [From:To] -45.00000 [deg] to 225.00000 [deg] (in 1/10000th deg: from 0xFFF92230 to 0x225510)
[/sick_scan_front] [1591372161.066961787] [ INFO] [SickScanCommon::init_scanner():1732]: MIN_ANG:   -2.356 [rad] -135.000 [deg]
[/sick_scan_front] [1591372161.067003693] [ INFO] [SickScanCommon::init_scanner():1733]: MAX_ANG:    2.356 [rad]  135.000 [deg]
[/sick_scan_front] [1591372161.067079020] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sWN LMPoutputRange 1 D05 FFF92230 225510<ETX>
[/sick_scan_front] [1591372161.069306567] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sFA A<ETX>
[/sick_scan_front] [1591372161.069359069] [ERROR] [SickScanCommon::sendSopasAndCheckAnswer():750]: Error Sopas answer mismatch Error unexpected Sopas Answer for request <STX>sWN LMPoutputRange 1 D05 FFF92230 225510<ETX>Answer= >>>sFA A<<<

[/sick_scan_front] [1591372161.069508057] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sRN LMPoutputRange<ETX>
[/sick_scan_front] [1591372161.070678287] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sRA LMPoutputRange 1 D05 FFF92230 225510<ETX>
[/sick_scan_front] [1591372161.070736499] [ INFO] [SickScanCommon::init_scanner():1885]: Angle resolution of scanner is 0.33330 [deg]  (in 1/10000th deg: 0xD05)
[/sick_scan_front] [1591372161.073313481] [ INFO] [SickScanCommon::init_scanner():1909]: MIN_ANG (after command verification):   -2.356 [rad] -135.000 [deg]
[/sick_scan_front] [1591372161.073357729] [ INFO] [SickScanCommon::init_scanner():1911]: MAX_ANG (after command verification):    2.356 [rad]  135.000 [deg]
[/sick_scan_front] [1591372161.073426061] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sWN LMDscandatacfg 01 00 1 1 0 0 00 0 0 0 1 1<ETX>
[/sick_scan_back] [1591372161.074287957] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sRN LocationName<ETX>
[/sick_scan_front] [1591372161.075703205] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sFA A<ETX>
[/sick_scan_front] [1591372161.075757267] [ERROR] [SickScanCommon::sendSopasAndCheckAnswer():750]: Error Sopas answer mismatch Error unexpected Sopas Answer for request <STX>sWN LMDscandatacfg 01 00 1 1 0 0 00 0 0 0 1 1<ETX>Answer= >>>sFA A<<<

[/sick_scan_front] [1591372161.075831035] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sRN LMDscandatacfg<ETX>
[/sick_scan_back] [1591372161.076558141] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sRA LocationName A beta1-back<ETX>
[/sick_scan_front] [1591372161.076972481] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sRA LMDscandatacfg 1 0 1 0 0 0 0 0 1 0 0 1<ETX>
[/sick_scan_back] [1591372161.077790102] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sRN LMPoutputRange<ETX>
[/sick_scan_front] [1591372161.078580328] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sMN LMCstartmeas<ETX>
[/sick_scan_back] [1591372161.078905216] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sRA LMPoutputRange 1 D05 FFF92230 225510<ETX>
[/sick_scan_back] [1591372161.078937802] [ INFO] [SickScanCommon::init_scanner():1721]: Angle resolution of scanner is 0.33330 [deg]  (in 1/10000th deg: 0xD05)
[/sick_scan_back] [1591372161.078957484] [ INFO] [SickScanCommon::init_scanner():1723]: [From:To] -45.00000 [deg] to 225.00000 [deg] (in 1/10000th deg: from 0xFFF92230 to 0x225510)
[/sick_scan_back] [1591372161.078981831] [ INFO] [SickScanCommon::init_scanner():1732]: MIN_ANG:   -2.356 [rad] -135.000 [deg]
[/sick_scan_back] [1591372161.079005518] [ INFO] [SickScanCommon::init_scanner():1733]: MAX_ANG:    2.356 [rad]  135.000 [deg]
[/sick_scan_back] [1591372161.079041561] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sWN LMPoutputRange 1 D05 FFF92230 225510<ETX>
[/sick_scan_front] [1591372161.079669349] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sFA 1<ETX>
[/sick_scan_front] [1591372161.079692388] [ERROR] [SickScanCommon::sendSopasAndCheckAnswer():750]: Error Sopas answer mismatch Command or Error message not definedAnswer= >>>sFA 1<<<

[/sick_scan_front] [1591372161.079726574] [ERROR] [SickScanCommon::init_scanner():2244]: Command or Error message not defined
[/sick_scan_front] [1591372161.079748990] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sMN Run<ETX>
[/sick_scan_back] [1591372161.080109117] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sFA A<ETX>
[/sick_scan_back] [1591372161.080137578] [ERROR] [SickScanCommon::sendSopasAndCheckAnswer():750]: Error Sopas answer mismatch Error unexpected Sopas Answer for request <STX>sWN LMPoutputRange 1 D05 FFF92230 225510<ETX>Answer= >>>sFA A<<<

[/sick_scan_back] [1591372161.080183106] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sRN LMPoutputRange<ETX>
[/sick_scan_front] [1591372161.081917162] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sAN Run 1<ETX>
[/sick_scan_front] [1591372161.081962641] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sEN LMDscandata 1<ETX>
[/sick_scan_back] [1591372161.082342933] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sRA LMPoutputRange 1 D05 FFF92230 225510<ETX>
[/sick_scan_back] [1591372161.082382281] [ INFO] [SickScanCommon::init_scanner():1885]: Angle resolution of scanner is 0.33330 [deg]  (in 1/10000th deg: 0xD05)
[/sick_scan_front] [1591372161.083066414] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sEA LMDscandata 1<ETX>
[/sick_scan_back] [1591372161.083881968] [ INFO] [SickScanCommon::init_scanner():1909]: MIN_ANG (after command verification):   -2.356 [rad] -135.000 [deg]
[/sick_scan_back] [1591372161.083919071] [ INFO] [SickScanCommon::init_scanner():1911]: MAX_ANG (after command verification):    2.356 [rad]  135.000 [deg]
[/sick_scan_back] [1591372161.083941803] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sWN LMDscandatacfg 01 00 1 1 0 0 00 0 0 0 1 1<ETX>
[/sick_scan_back] [1591372161.085029091] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sFA A<ETX>
[/sick_scan_back] [1591372161.085071723] [ERROR] [SickScanCommon::sendSopasAndCheckAnswer():750]: Error Sopas answer mismatch Error unexpected Sopas Answer for request <STX>sWN LMDscandatacfg 01 00 1 1 0 0 00 0 0 0 1 1<ETX>Answer= >>>sFA A<<<

[/sick_scan_back] [1591372161.085098133] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sRN LMDscandatacfg<ETX>
[/sick_scan_back] [1591372161.086212068] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sRA LMDscandatacfg 1 0 1 0 0 0 0 0 1 0 0 1<ETX>
[/sick_scan_back] [1591372161.087236901] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sMN LMCstartmeas<ETX>
[/sick_scan_back] [1591372161.089414073] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sFA 1<ETX>
[/sick_scan_back] [1591372161.089450352] [ERROR] [SickScanCommon::sendSopasAndCheckAnswer():750]: Error Sopas answer mismatch Command or Error message not definedAnswer= >>>sFA 1<<<

[/sick_scan_back] [1591372161.089493173] [ERROR] [SickScanCommon::init_scanner():2244]: Command or Error message not defined
[/sick_scan_back] [1591372161.089537408] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sMN Run<ETX>
[/sick_scan_back] [1591372161.090640815] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sAN Run 1<ETX>
[/sick_scan_back] [1591372161.090662248] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():717]: Sending  : <STX>sEN LMDscandata 1<ETX>
[/sick_scan_back] [1591372161.091796792] [ INFO] [SickScanCommon::sendSopasAndCheckAnswer():723]: Receiving: <STX>sEA LMDscandata 1<ETX>

**Comment by stg710** [comment]
Hi @rachel-spykerman, the launch file "sick_tim_7xxS.launch" works with the default password stated in the manual on page 32
https://cdn.sick.com/media/docs/4/54/254/Operating_instructions_TiM781S_en_IM0083254.PDF

**Comment by rachel-spykerman** [comment]
So both LIDAR's I set up had their passwords changed from SICKSAFE to something else. Does sick_scan expect the default password to be used? If changed back to the default password, would the above setAccessMode errors be resolved? I run into other errors with EIHstCola, LMPoutputRange, and LMDscandatacfg. When checking the parameters I've set in my launch files and the parameters I've set in Sopas, I don't see any mismatch. At this point, I'm assuming these errors occur because the setAccessMode failed.

**Comment by michael1309** [comment]
The hash codes for the access mode stored in the code are encoded in the following commands:
```
    sopasCmdVec[CMD_SET_ACCESS_MODE_3] = "\x02sMN SetAccessMode 3 F4724744\x03\0";
    sopasCmdVec[CMD_SET_ACCESS_MODE_3_SAFETY_SCANNER] = "\x02sMN SetAccessMode 3 6FD62C05\x03\0";
```
For the safety scanner, the hash code '6FD62C05' corresponds to the standard password SICKSAFE (according to section 6.5.6 of the above mentioned document https://cdn.sick.com/media/docs/4/54/254/Operating_instructions_TiM781S_en_IM0083254.PDF ) of the safety scanner.

Have you tried to reset the scanner to the delivery status? After that, logging in should be possible again.  Otherwise, I recommend to contact the support team to reset the lidar to the default settings.

**Comment by michael1309** [comment]
![image](https://user-images.githubusercontent.com/33296049/84121160-0f9b9880-aa37-11ea-9086-b99ad20972cb.png)
![image](https://user-images.githubusercontent.com/33296049/84121209-1fb37800-aa37-11ea-9f16-b76ddfeae0cf.png)

**Comment by michael1309** [comment]
If you have now assigned your own password, you must patch the code according to this calculation. 
sopasCmdVec[CMD_SET_ACCESS_MODE_3_SAFETY_SCANNER] = "\x02sMN SetAccessMode 3 **6FD62C05**\x03\0";

**Comment by rachel-spykerman** [comment]
Great, thank you! That worked.
