### ISSUE TITLE
3D Lidar

### ISSUE THREAD

**Issue by THLL245** [SICKAG/sick_scan#93]
I might be missing something here but the MRS1xxx and MRS6xxx are meant to be 3D lidars, going through the URDF files I am not seeing "vertical" elements in the "ray" so its only being used as a 1 layer lidar? Is there not a urdf setup or example for this yet?

**Comment by michael1309** [comment]
You  are  right. These are 3d lidars and publish 3d pointcloud data. The urdf files are not relevant for these two lidars at the moment.

**Comment by michael1309** [comment]
Please feel free to add the specific models. Maybe you can find one on the SICK website. Pull requests are welcome.
