### ISSUE TITLE
Dependency on ROS-Metapackage prevents usage as dependency in other packages

### ISSUE THREAD

**Issue by pichlermarc** [SICKAG/sick_scan#96]
I'm currently working on a project where I'm using a SICK LMS111 and this package.

After I upgraded the package from `1.6.0` to `1.7.7`, I tried to build one of my packages which depends on `sick_scan` in order to use `sick_scan`'s messages. However, the build-process now fails because neither `perception_pclConfig.cmake` nor `perception_pcl-config.cmake` do exist, as `perception_pcl` is a ROS-Metapackage and therefore only contains a `package.xml` and no `cmake/` directory when it is installed.

As far as I know, it is a general recommendation to not use ROS-Metapackages as dependencies, but to use specific packages instead (see [here](https://www.ros.org/reps/rep-0127.html#metapackage)).

My suggestion would be to replace it with the previously used specific packages:
```
<exec_depend>pcl_conversions</exec_depend>
<exec_depend>pcl_ros</exec_depend>
```

**Comment by michael1309** [comment]
This is already fixed as mentioned in the pull request.
