### ISSUE TITLE
About time stamp

### ISSUE THREAD

**Issue by chance2006** [SICKAG/sick_scan#98]
Dear Sir:
I need to use the TIM‘s time stamp(time stamp,Time since start up in µs ,Time of transmission in µs), Because I want to Syn. with other device. 
![image](https://user-images.githubusercontent.com/42546230/90868056-de413080-e3c8-11ea-9430-9ccb861e91a7.png)

Coud you help me to acchive it?
 
Best Regards!
Bob Hao

**Comment by michael1309** [comment]
HI Bob,

exactly for this case we introduced the mechanism of the so called SoftwarePLL. 
You can find more information here: https://github.com/SICKAG/sick_scan/blob/master/doc/software_pll.md

The mechanism can be switched on by setting the flag `sw_pll_only_publish` to true.
Best regards,
Michael

**Comment by chance2006** [comment]
Dear Sir：
Thanks very much！I have understood it.
Best Regards!
Chester Hao
